[35mDEBUG   [0m faker.factory:factory.py:78 Looking for locale `en_US` in provider `faker.providers.address`.
[35mDEBUG   [0m faker.factory:factory.py:97 Provider `faker.providers.address` has been localized to `en_US`.
[35mDEBUG   [0m faker.factory:factory.py:78 Looking for locale `en_US` in provider `faker.providers.automotive`.
[35mDEBUG   [0m faker.factory:factory.py:97 Provider `faker.providers.automotive` has been localized to `en_US`.
[35mDEBUG   [0m faker.factory:factory.py:78 Looking for locale `en_US` in provider `faker.providers.bank`.
[35mDEBUG   [0m faker.factory:factory.py:88 Specified locale `en_US` is not available for provider `faker.providers.bank`. Locale reset to `en_GB` for this provider.
[35mDEBUG   [0m faker.factory:factory.py:78 Looking for locale `en_US` in provider `faker.providers.barcode`.
[35mDEBUG   [0m faker.factory:factory.py:97 Provider `faker.providers.barcode` has been localized to `en_US`.
[35mDEBUG   [0m faker.factory:factory.py:78 Looking for locale `en_US` in provider `faker.providers.color`.
[35mDEBUG   [0m faker.factory:factory.py:97 Provider `faker.providers.color` has been localized to `en_US`.
[35mDEBUG   [0m faker.factory:factory.py:78 Looking for locale `en_US` in provider `faker.providers.company`.
[35mDEBUG   [0m faker.factory:factory.py:97 Provider `faker.providers.company` has been localized to `en_US`.
[35mDEBUG   [0m faker.factory:factory.py:78 Looking for locale `en_US` in provider `faker.providers.credit_card`.
[35mDEBUG   [0m faker.factory:factory.py:97 Provider `faker.providers.credit_card` has been localized to `en_US`.
[35mDEBUG   [0m faker.factory:factory.py:78 Looking for locale `en_US` in provider `faker.providers.currency`.
[35mDEBUG   [0m faker.factory:factory.py:97 Provider `faker.providers.currency` has been localized to `en_US`.
[35mDEBUG   [0m faker.factory:factory.py:78 Looking for locale `en_US` in provider `faker.providers.date_time`.
[35mDEBUG   [0m faker.factory:factory.py:97 Provider `faker.providers.date_time` has been localized to `en_US`.
[35mDEBUG   [0m faker.factory:factory.py:109 Provider `faker.providers.file` does not feature localization. Specified locale `en_US` is not utilized for this provider.
[35mDEBUG   [0m faker.factory:factory.py:78 Looking for locale `en_US` in provider `faker.providers.geo`.
[35mDEBUG   [0m faker.factory:factory.py:97 Provider `faker.providers.geo` has been localized to `en_US`.
[35mDEBUG   [0m faker.factory:factory.py:78 Looking for locale `en_US` in provider `faker.providers.internet`.
[35mDEBUG   [0m faker.factory:factory.py:97 Provider `faker.providers.internet` has been localized to `en_US`.
[35mDEBUG   [0m faker.factory:factory.py:109 Provider `faker.providers.isbn` does not feature localization. Specified locale `en_US` is not utilized for this provider.
[35mDEBUG   [0m faker.factory:factory.py:78 Looking for locale `en_US` in provider `faker.providers.job`.
[35mDEBUG   [0m faker.factory:factory.py:97 Provider `faker.providers.job` has been localized to `en_US`.
[35mDEBUG   [0m faker.factory:factory.py:78 Looking for locale `en_US` in provider `faker.providers.lorem`.
[35mDEBUG   [0m faker.factory:factory.py:97 Provider `faker.providers.lorem` has been localized to `en_US`.
[35mDEBUG   [0m faker.factory:factory.py:78 Looking for locale `en_US` in provider `faker.providers.misc`.
[35mDEBUG   [0m faker.factory:factory.py:97 Provider `faker.providers.misc` has been localized to `en_US`.
[35mDEBUG   [0m faker.factory:factory.py:78 Looking for locale `en_US` in provider `faker.providers.person`.
[35mDEBUG   [0m faker.factory:factory.py:97 Provider `faker.providers.person` has been localized to `en_US`.
[35mDEBUG   [0m faker.factory:factory.py:78 Looking for locale `en_US` in provider `faker.providers.phone_number`.
[35mDEBUG   [0m faker.factory:factory.py:97 Provider `faker.providers.phone_number` has been localized to `en_US`.
[35mDEBUG   [0m faker.factory:factory.py:109 Provider `faker.providers.profile` does not feature localization. Specified locale `en_US` is not utilized for this provider.
[35mDEBUG   [0m faker.factory:factory.py:109 Provider `faker.providers.python` does not feature localization. Specified locale `en_US` is not utilized for this provider.
[35mDEBUG   [0m faker.factory:factory.py:78 Looking for locale `en_US` in provider `faker.providers.ssn`.
[35mDEBUG   [0m faker.factory:factory.py:97 Provider `faker.providers.ssn` has been localized to `en_US`.
[35mDEBUG   [0m faker.factory:factory.py:109 Provider `faker.providers.user_agent` does not feature localization. Specified locale `en_US` is not utilized for this provider.
[32mINFO    [0m WDM:logger.py:26 

[32mINFO    [0m WDM:logger.py:26 ====== WebDriver manager ======
[32mINFO    [0m WDM:logger.py:26 Current google-chrome version is 100.0.4896
[32mINFO    [0m WDM:logger.py:26 Get LATEST chromedriver version for 100.0.4896 google-chrome
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1001 Starting new HTTPS connection (1): chromedriver.storage.googleapis.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://chromedriver.storage.googleapis.com:443 "GET /LATEST_RELEASE_100.0.4896 HTTP/1.1" 200 13
[32mINFO    [0m WDM:logger.py:26 Driver [C:\Users\User\.wdm\drivers\chromedriver\win32\100.0.4896.60\chromedriver.exe] found in cache
[35mDEBUG   [0m selenium.webdriver.remote.remote_connection:remote_connection.py:347 POST http://localhost:49258/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "pageLoadStrategy": "normal", "goog:chromeOptions": {"extensions": [], "args": []}}}, "desiredCapabilities": {"browserName": "chrome", "pageLoadStrategy": "normal", "goog:chromeOptions": {"extensions": [], "args": []}}}
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:228 Starting new HTTP connection (1): localhost:49258
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 http://localhost:49258 "POST /session HTTP/1.1" 200 790
[35mDEBUG   [0m selenium.webdriver.remote.remote_connection:remote_connection.py:398 Finished Request
[35mDEBUG   [0m selenium.webdriver.remote.remote_connection:remote_connection.py:347 POST http://localhost:49258/session/3ef0b0386ea2e2b28e3b5148fdcec035/url {"url": "https://www.saucedemo.com/"}
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 http://localhost:49258 "POST /session/3ef0b0386ea2e2b28e3b5148fdcec035/url HTTP/1.1" 200 14
[35mDEBUG   [0m selenium.webdriver.remote.remote_connection:remote_connection.py:398 Finished Request
[35mDEBUG   [0m selenium.webdriver.remote.remote_connection:remote_connection.py:347 POST http://localhost:49258/session/3ef0b0386ea2e2b28e3b5148fdcec035/window/maximize {}
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 http://localhost:49258 "POST /session/3ef0b0386ea2e2b28e3b5148fdcec035/window/maximize HTTP/1.1" 200 51
[35mDEBUG   [0m selenium.webdriver.remote.remote_connection:remote_connection.py:398 Finished Request
[35mDEBUG   [0m selenium.webdriver.remote.remote_connection:remote_connection.py:347 GET http://localhost:49258/session/3ef0b0386ea2e2b28e3b5148fdcec035/title {}
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 http://localhost:49258 "GET /session/3ef0b0386ea2e2b28e3b5148fdcec035/title HTTP/1.1" 200 21
[35mDEBUG   [0m selenium.webdriver.remote.remote_connection:remote_connection.py:398 Finished Request
[33mWARNING [0m root:test_Login.py:23 Launching browser
[32mINFO    [0m root:test_Login.py:26 Enter Username
[35mDEBUG   [0m selenium.webdriver.remote.remote_connection:remote_connection.py:347 POST http://localhost:49258/session/3ef0b0386ea2e2b28e3b5148fdcec035/element {"using": "xpath", "value": "//*[@id=\"user-name\"]"}
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 http://localhost:49258 "POST /session/3ef0b0386ea2e2b28e3b5148fdcec035/element HTTP/1.1" 200 88
[35mDEBUG   [0m selenium.webdriver.remote.remote_connection:remote_connection.py:398 Finished Request
[35mDEBUG   [0m selenium.webdriver.remote.remote_connection:remote_connection.py:347 POST http://localhost:49258/session/3ef0b0386ea2e2b28e3b5148fdcec035/element/6765670c-b00f-4f05-8abf-1583332810f1/value {"text": "standard_user", "value": ["s", "t", "a", "n", "d", "a", "r", "d", "_", "u", "s", "e", "r"], "id": "6765670c-b00f-4f05-8abf-1583332810f1"}
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 http://localhost:49258 "POST /session/3ef0b0386ea2e2b28e3b5148fdcec035/element/6765670c-b00f-4f05-8abf-1583332810f1/value HTTP/1.1" 200 14
[35mDEBUG   [0m selenium.webdriver.remote.remote_connection:remote_connection.py:398 Finished Request
[35mDEBUG   [0m selenium.webdriver.remote.remote_connection:remote_connection.py:347 POST http://localhost:49258/session/3ef0b0386ea2e2b28e3b5148fdcec035/element {"using": "css selector", "value": "[id=\"password\"]"}
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 http://localhost:49258 "POST /session/3ef0b0386ea2e2b28e3b5148fdcec035/element HTTP/1.1" 200 88
[35mDEBUG   [0m selenium.webdriver.remote.remote_connection:remote_connection.py:398 Finished Request
[35mDEBUG   [0m selenium.webdriver.remote.remote_connection:remote_connection.py:347 POST http://localhost:49258/session/3ef0b0386ea2e2b28e3b5148fdcec035/element/60eb5d22-6b64-4443-a50c-12c9507914ad/value {"text": "secret_sauce", "value": ["s", "e", "c", "r", "e", "t", "_", "s", "a", "u", "c", "e"], "id": "60eb5d22-6b64-4443-a50c-12c9507914ad"}
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 http://localhost:49258 "POST /session/3ef0b0386ea2e2b28e3b5148fdcec035/element/60eb5d22-6b64-4443-a50c-12c9507914ad/value HTTP/1.1" 200 14
[35mDEBUG   [0m selenium.webdriver.remote.remote_connection:remote_connection.py:398 Finished Request
[35mDEBUG   [0m selenium.webdriver.remote.remote_connection:remote_connection.py:347 POST http://localhost:49258/session/3ef0b0386ea2e2b28e3b5148fdcec035/element {"using": "xpath", "value": "//*[@id=\"login-button\"]"}
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 http://localhost:49258 "POST /session/3ef0b0386ea2e2b28e3b5148fdcec035/element HTTP/1.1" 200 88
[35mDEBUG   [0m selenium.webdriver.remote.remote_connection:remote_connection.py:398 Finished Request
[35mDEBUG   [0m selenium.webdriver.remote.remote_connection:remote_connection.py:347 POST http://localhost:49258/session/3ef0b0386ea2e2b28e3b5148fdcec035/element/71ad2fa3-135e-41c7-ba50-6dd082401796/click {"id": "71ad2fa3-135e-41c7-ba50-6dd082401796"}
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 http://localhost:49258 "POST /session/3ef0b0386ea2e2b28e3b5148fdcec035/element/71ad2fa3-135e-41c7-ba50-6dd082401796/click HTTP/1.1" 200 14
[35mDEBUG   [0m selenium.webdriver.remote.remote_connection:remote_connection.py:398 Finished Request
[35mDEBUG   [0m selenium.webdriver.remote.remote_connection:remote_connection.py:347 POST http://localhost:49258/session/3ef0b0386ea2e2b28e3b5148fdcec035/element {"using": "css selector", "value": "[id=\"react-burger-menu-btn\"]"}
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 http://localhost:49258 "POST /session/3ef0b0386ea2e2b28e3b5148fdcec035/element HTTP/1.1" 200 88
[35mDEBUG   [0m selenium.webdriver.remote.remote_connection:remote_connection.py:398 Finished Request
[35mDEBUG   [0m selenium.webdriver.remote.remote_connection:remote_connection.py:347 POST http://localhost:49258/session/3ef0b0386ea2e2b28e3b5148fdcec035/element/d9c6f3e7-4bd8-476a-822e-b97e31bac623/click {"id": "d9c6f3e7-4bd8-476a-822e-b97e31bac623"}
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 http://localhost:49258 "POST /session/3ef0b0386ea2e2b28e3b5148fdcec035/element/d9c6f3e7-4bd8-476a-822e-b97e31bac623/click HTTP/1.1" 200 14
[35mDEBUG   [0m selenium.webdriver.remote.remote_connection:remote_connection.py:398 Finished Request
[35mDEBUG   [0m selenium.webdriver.remote.remote_connection:remote_connection.py:347 GET http://localhost:49258/session/3ef0b0386ea2e2b28e3b5148fdcec035/screenshot {}
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 http://localhost:49258 "GET /session/3ef0b0386ea2e2b28e3b5148fdcec035/screenshot HTTP/1.1" 200 88060
[35mDEBUG   [0m selenium.webdriver.remote.remote_connection:remote_connection.py:398 Finished Request